### ISSUE TITLE
Please add in the joyride in type list via MLPTF TranSPOT.

### ISSUE THREAD

**Issue by hoadison1999** [kwongtn/rosak_firebase#10]
![Screenshot (872)](https://user-images.githubusercontent.com/112250812/231239645-fd5056dd-4f4e-4fab-bee9-a4f9dc66154a.png)
Hi,

Please suggest to add in the joyride in type list via MLPTF TranSPOT.

Thank you.

**Comment by kwongtn** [comment]
Hi @hoadison1999 
Joyride is considered as 'Just Spotting'. Technically it would not serve any informational purpose on whether someone is spotting during daily commute or during joyride, as the goal of our system is to track appearances of vehicles.
